import:
  - ~/.console/dracula.yml

cursor:
    style:
        blinking: Always
        blink_interval: 500
        shape: Beam
font:
  normal:
    family: Meslo LG M
    style: Regular

  bold:
    family: Meslo LG M
    style: Bold

  italic:
    family: Meslo LG M
    style: Italic

  size: 9

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false
